/**
 * AI Page Builder (Free Path)
 * Generates simple, clean HTML/CSS/JS scaffolds based on a natural language description
 * without requiring paid AI providers. Deterministic and template-driven.
 */

function normalize(text) {
  const s = String(text || '').trim();
  return s.length > 0 ? s : 'My Project';
}

function parseDescription(desc) {
  const d = String(desc || '').toLowerCase();
  const sections = [];
  if (/hero|landing|واجهة|ترحيب/.test(d)) sections.push('hero');
  if (/features|ميزات|خصائص/.test(d)) sections.push('features');
  if (/pricing|الأسعار|باقة/.test(d)) sections.push('pricing');
  if (/contact|اتصال|تواصل/.test(d)) sections.push('contact');
  if (sections.length === 0) sections.push('hero','features','contact');
  const palette = /dark|داكن/.test(d) ? { bg: '#0b1020', fg: '#e5e7eb', accent: '#f59e0b' } : { bg: '#0f172a', fg: '#e5e7eb', accent: '#22d3ee' };
  const lang = /عرب|arab|arabic|العربية|ar\b/.test(d) ? 'ar' : 'en';
  return { sections, palette, lang };
}

function genHtml({ title, tagline, sections, lang }) {
  const dir = lang === 'ar' ? 'rtl' : 'ltr';
  const tFeatures = lang === 'ar' ? 'المميزات' : 'Features';
  const tPricing = lang === 'ar' ? 'الخطط والأسعار' : 'Pricing';
  const tContact = lang === 'ar' ? 'تواصل معنا' : 'Contact Us';
  const blocks = {
    hero: `<section class="hero"><h1>${title}</h1><p>${tagline}</p><a class="cta" href="#contact">${lang==='ar'?'ابدأ الآن':'Get Started'}</a></section>`,
    features: `<section class="features"><h2>${tFeatures}</h2><div class="grid"><div class="card">UI</div><div class="card">API</div><div class="card">Deploy</div></div></section>`,
    pricing: `<section class="pricing"><h2>${tPricing}</h2><div class="plans"><div class="plan"><h3>${lang==='ar'?'مجاني':'Free'}</h3><p>${lang==='ar'?'ابدأ بلا تكلفة':'Start at no cost'}</p></div><div class="plan"><h3>${lang==='ar'?'احترافي':'Pro'}</h3><p>${lang==='ar'?'مزايا إضافية':'Extra features'}</p></div></div></section>`,
    contact: `<section class="contact" id="contact"><h2>${tContact}</h2><form><input type="email" placeholder="${lang==='ar'?'بريدك الإلكتروني':'Your email'}" /><button type="button">${lang==='ar'?'إرسال':'Send'}</button></form></section>`
  };
  const body = sections.map(s => blocks[s] || '').join('\n');
  return `<!doctype html><html lang="${lang}" dir="${dir}"><head><meta charset="utf-8"/><meta name="viewport" content="width=device-width, initial-scale=1"/><title>${title}</title><link rel="stylesheet" href="styles.css"/></head><body>${body}<script src="script.js"></script></body></html>`;
}

function genCss({ palette }) {
  return `:root{--bg:${palette.bg};--fg:${palette.fg};--accent:${palette.accent}}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font-family:system-ui,Segoe UI,Roboto,Arial,sans-serif;line-height:1.6}
.hero{padding:64px 24px;text-align:center}.hero h1{font-size:40px;margin:0 0 12px}.hero p{opacity:.85;margin:0 0 16px}.cta{display:inline-block;background:var(--accent);color:#000;padding:10px 16px;border-radius:10px;text-decoration:none;border:1px solid #000}
.features,.pricing,.contact{padding:40px 24px;max-width:980px;margin:0 auto}.features h2,.pricing h2,.contact h2{margin:0 0 16px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.card{background:#111827;border:1px solid #374151;border-radius:12px;padding:20px;text-align:center}
.plans{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.plan{background:#111827;border:1px solid #374151;border-radius:12px;padding:20px}
.contact form{display:flex;gap:8px;flex-wrap:wrap}.contact input{flex:1;min-width:240px;padding:10px;border-radius:8px;border:1px solid #374151;background:#0b1220;color:var(--fg)}.contact button{background:var(--accent);color:#000;border:1px solid #000;border-radius:8px;padding:10px 16px}`;
}

function genJs({ lang }) {
  const ok = lang==='ar' ? 'تم الإرسال' : 'Sent';
  return `document.addEventListener('click',(e)=>{if(e.target&&e.target.matches('button')){alert('${ok}')}})`;
}

export async function generatePageCode({ description, projectType = 'page', style }) {
  const title = normalize(description);
  const tagline = style ? normalize(style) : (description || '').trim().slice(0, 80);
  const { sections, palette, lang } = parseDescription(description);
  const html = genHtml({ title, tagline, sections, lang });
  const css = genCss({ palette });
  const js = genJs({ lang });
  const files = [
    { path: 'index.html', content: html },
    { path: 'styles.css', content: css },
    { path: 'script.js', content: js },
    { path: 'README.md', content: `# ${title}\n\nGenerated by JOE Free Builder\n\nSections: ${sections.join(', ')}` }
  ];
  if (projectType === 'app') {
    files.push({ path: 'pages/about.html', content: '<h2>About</h2>' });
    files.push({ path: 'pages/contact.html', content: '<h2>Contact</h2>' });
  }
  return { success: true, files, language: lang };
}

export default { generatePageCode };
