
/**
 * 🚀 JOE Advanced Engine - UPGRADED & REFACTORED
 * The most powerful and intelligent engine, now integrated with the Advanced Memory Manager and refactored tools.
 *
 * @module joeAdvancedEngine
 * @version 7.0.0 - Unified Edition
 * @author XElite Solutions (Refactored by AGI)
 */

import OpenAI from 'openai';
import { EventEmitter } from 'events';
import fs from 'fs/promises';
import { exec } from 'child_process';
import { promisify } from 'util';
import crypto from 'crypto';
import os from 'os';

// Unified Tool Imports from the single source of truth: tools_refactored
import { fileSystemTools } from '../../tools_refactored/fileSystemTools.mjs';
import { gitTools } from '../../tools_refactored/gitTools.mjs';
import { searchTools } from '../../tools_refactored/searchTools.mjs';
import { webSearchTools } from '../../tools_refactored/webSearchTools.mjs';
import { buildTools } from '../../tools_refactored/buildTools.mjs';
import { memoryTools } from '../../tools_refactored/memoryTools.mjs';
import { multimodalTools } from '../../tools_refactored/multimodalTools.mjs';
import { automationTools } from '../../tools_refactored/automationTools.mjs';
import { advancedBrowserTools } from '../../tools_refactored/advancedBrowserTools.mjs';
import { advancedSearchTools } from '../../tools_refactored/advancedSearchTools.mjs';
import { softwareDevelopmentTools } from '../../tools_refactored/softwareDevelopmentTools.mjs';
import { ecommerceTools } from '../../tools_refactored/ecommerceTools.mjs';
import { deploymentTools } from '../../tools_refactored/deploymentTools.mjs';

// System-Wide Component Imports
import MANUS_STYLE_PROMPT from '../../prompts/manusStylePrompt.mjs';
import { memoryManager } from '../memory/memory.service.mjs'; // <<< INTEGRATED ADVANCED MEMORY

const execAsync = promisify(exec);

// OpenAI Configuration
let openai;
if (process.env.OPENAI_API_KEY) {
  openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY
  });
} else {
  console.warn('⚠️ OPENAI_API_KEY is missing. Joe AI will be limited.');
}

// =========================
// 🎯 Advanced Event System (Kept for granular, in-task progress)
// =========================

class JoeEventEmitter extends EventEmitter {
  constructor() {
    super();
    this.setMaxListeners(100);
  }

  emitProgress(userId, taskId, progress, message) {
    this.emit('progress', { type: 'progress', userId, taskId, progress, message, timestamp: new Date() });
  }

  emitError(userId, error, context) {
    this.emit('error', { type: 'error', userId, error: error.message, stack: error.stack, context, timestamp: new Date() });
  }
}

const joeEvents = new JoeEventEmitter();


// =========================
// 🎯 Intelligent Decision Maker (Simplified, relies on memory for learning)
// =========================

class IntelligentDecisionMaker {
  constructor() {
    // Patterns can be dynamically loaded from memoryManager in the future
    this.patterns = {
      search: { patterns: [/ابحث|بحث|search|find/i], confidence: 0.9, tools: ['search_web'] },
      code: { patterns: [/كود|برمجة|code/i], confidence: 0.85, tools: ['generate_code'] },
      image: { patterns: [/صورة|image/i], confidence: 0.95, tools: ['generateImage'] },
      file: { patterns: [/ملف|file/i], confidence: 0.9, tools: ['readFile', 'writeFile'] },
    };
  }

  detectRequestType(message) {
    let bestMatch = { type: 'general', confidence: 0 };
    for (const [type, config] of Object.entries(this.patterns)) {
      for (const pattern of config.patterns) {
        if (pattern.test(message) && config.confidence > bestMatch.confidence) {
          bestMatch = { type, confidence: config.confidence };
        }
      }
    }
    return bestMatch;
  }

  estimateComplexity(message) {
    let complexity = 1;
    if (message.length > 200) complexity += 1;
    if (message.length > 500) complexity += 1;
    if (/متقدم|advanced|complex/i.test(message)) complexity += 2;
    const taskIndicators = message.match(/و|and|ثم|then|,/g);
    if (taskIndicators) complexity += Math.min(taskIndicators.length, 3);
    return Math.min(complexity, 10);
  }
}

const decisionMaker = new IntelligentDecisionMaker();

// =========================
// 🛠️ All Tools (Dynamically defined for OpenAI)
// =========================

const ALL_TOOLS = [
  // This list can be dynamically generated by a ToolManager in the future
  { type: 'function', function: { name: 'readFile', description: 'Read the content of a file', parameters: { type: 'object', properties: { filePath: { type: 'string' } }, required: ['filePath'] } } },
  { type: 'function', function: { name: 'writeFile', description: 'Write content to a file', parameters: { type: 'object', properties: { filePath: { type: 'string' }, content: { type: 'string' } }, required: ['filePath', 'content'] } } },
  { type: 'function', function: { name: 'listDirectory', description: 'List files in a directory', parameters: { type: 'object', properties: { dirPath: { type: 'string' } }, required: ['dirPath'] } } },
  { type: 'function', function: { name: 'gitQuickCommit', description: 'Perform a quick Git commit', parameters: { type: 'object', properties: { message: { type: 'string' } }, required: ['message'] } } },
  { type: 'function', function: { name: 'search_web', description: 'Search the web for information', parameters: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] } } },
  { type: 'function', function: { name: 'generateImage', description: 'Generate an image from a prompt', parameters: { type: 'object', properties: { prompt: { type: 'string' } }, required: ['prompt'] } } },
  { type: 'function', function: { name: 'create_react_project', description: 'Create a new React project', parameters: { type: 'object', properties: { projectName: { type: 'string' } }, required: ['projectName'] } } },
  { type: 'function', function: { name: 'execute_command', description: 'Execute a terminal command', parameters: { type: 'object', properties: { command: { type: 'string' } }, required: ['command'] } } },
  { type: 'function', function: { name: 'generate_code', description: 'Generate a code snippet', parameters: { type: 'object', properties: { description: { type: 'string' }, language: { type: 'string' } }, required: ['description', 'language'] } } },
];

// =========================
// ⚙️ Unified Tool Executor
// =========================

async function executeFunction(functionName, args, userId = 'default') {
  const startTime = Date.now();
  try {
    joeEvents.emitProgress(userId, functionName, 0, `Starting ${functionName}`);

    let result;
    // The switch now calls the correctly imported tool modules
    switch (functionName) {
      case 'readFile': result = await fileSystemTools.readFile(args.filePath); break;
      case 'writeFile': result = await fileSystemTools.writeFile(args.filePath, args.content); break;
      case 'editFile': result = await fileSystemTools.editFile(args.filePath, args.findText, args.replaceText); break;
      case 'listDirectory': result = await fileSystemTools.listDirectory(args.dirPath); break;
      case 'deleteFile': result = await fileSystemTools.deleteFile(args.filePath); break;
      case 'gitQuickCommit': result = await gitTools.gitQuickCommit(args.message); break;
      case 'searchInFiles': result = await searchTools.searchInFiles(args.query); break;
      case 'search_web': result = await webSearchTools.searchWeb(args.query); break;
      case 'generateImage': result = await multimodalTools.generateImage(args.prompt); break;
      case 'create_react_project': result = await softwareDevelopmentTools.createReactProject(args.projectName); break;
      case 'execute_command': result = await executeCommand(args.command); break;
      case 'generate_code': result = await generateCode(args.description, args.language); break;
      default: throw new Error(`Unknown function: ${functionName}`);
    }

    joeEvents.emitProgress(userId, functionName, 100, `Completed ${functionName}`);
    return { success: true, result, executionTime: Date.now() - startTime };
  } catch (error) {
    joeEvents.emitError(userId, error, { functionName, args });
    return { success: false, error: error.message };
  }
}

// Helper Functions (can be moved to a 'utils' module)
async function generateCode(description, language) {
    const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
            { role: 'system', content: `You are a helpful ${language} programmer.` },
            { role: 'user', content: description }
        ]
    });
    return { success: true, code: response.choices[0].message.content };
}

async function executeCommand(command) {
  const { stdout, stderr } = await execAsync(command);
  return { success: true, stdout, stderr };
}


// =========================
// 🚀 Main Processing Function
// =========================

async function processMessage(userId, message, sessionId) {
  const startTime = Date.now();
  console.log(`
🤖 JOE v7 Processing: "${message.substring(0, 50)}..." for User: ${userId}`);

  // 1. Retrieve Conversation Context from Advanced Memory Manager
  const conversationHistory = await memoryManager.getConversationContext(userId, { limit: 15 });

  const requestType = decisionMaker.detectRequestType(message);
  const complexity = decisionMaker.estimateComplexity(message);
  console.log(`📊 Type: ${requestType.type} | Complexity: ${complexity}/10`);

  const messages = [
    { role: 'system', content: MANUS_STYLE_PROMPT },
    // Format history for the LLM
    ...conversationHistory.map(item => ({
        role: item.command.role || 'user', // Assuming 'user' if not specified
        content: item.command.content || item.command
    })).reverse(), // Reverse to have the latest message last
    { role: 'user', content: message }
  ];

  if (!openai) {
    throw new Error('OPENAI_API_KEY is not configured.');
  }

  // 2. Main LLM Call with Tools
  let response = await openai.chat.completions.create({
    model: 'gpt-4o',
    messages,
    tools: ALL_TOOLS,
    tool_choice: 'auto',
    temperature: 0.7,
    max_tokens: 4000
  });

  let finalResponse = response.choices[0].message;
  const toolCalls = finalResponse.tool_calls || [];
  let toolResults = [];

  // 3. Execute Tool Calls if any
  if (toolCalls.length > 0) {
    console.log(`🔧 Executing ${toolCalls.length} tool(s)...`);
    const toolMessages = [finalResponse];

    for (const toolCall of toolCalls) {
      const functionName = toolCall.function.name;
      const args = JSON.parse(toolCall.function.arguments);

      console.log(`⚡ ${functionName}(${JSON.stringify(args).substring(0, 50)}...)`);
      const result = await executeFunction(functionName, args, userId);
      toolResults.push({ tool: functionName, args, result });

      toolMessages.push({
        role: 'tool',
        tool_call_id: toolCall.id,
        content: JSON.stringify(result)
      });
    }

    // 4. Second LLM Call to Synthesize Tool Results
    const secondResponse = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [...messages, ...toolMessages],
      temperature: 0.7,
      max_tokens: 4000
    });
    finalResponse = secondResponse.choices[0].message;
  }

  const duration = Date.now() - startTime;

  // 5. Save the complete interaction to the Advanced Memory Manager
  await memoryManager.saveInteraction(userId, message, finalResponse.content, {
      sessionId,
      intent: requestType.type,
      service: 'joe-advanced-v7',
      complexity,
      duration,
      toolResults,
      tokens: response.usage?.total_tokens
  });

  return {
    response: finalResponse.content,
    toolsUsed: toolCalls.map(tc => tc.function.name),
    requestType: requestType.type,
    complexity
  };
}

// =========================
// 📤 Exports
// =========================

export {
  processMessage,
  executeFunction,
  decisionMaker,
  joeEvents,
  ALL_TOOLS
};

export default {
  processMessage,
  executeFunction,
  decision: decisionMaker,
  events: joeEvents,
  tools: ALL_TOOLS,
  version: '7.0.0',
  name: 'JOE Advanced Engine - Unified Edition'
};

console.log('🚀 JOE Advanced Engine v7.0.0 (Unified) Loaded Successfully!');
console.log('🧠 Integrated with Advanced Memory Manager.');
console.log(`🛠️ All tools sourced from 'tools_refactored'.`);
