
/**
 * Project Generator Tool (Facade) - The User-Friendly Interface
 * This tool acts as a simplified facade for the complex, class-based AdvancedProjectTools engine.
 * It exposes powerful project generation capabilities as simple, discoverable functions for the Planner.
 * @version 1.0.0
 */

import { projectTools } from './project.tool.mjs'; // Importing the powerful, complex engine
import { promises as fs } from 'fs';
import path from 'path';

// A helper function to save the generated files to disk
async function saveProjectToDisk(projectId, files) {
    const outputDir = path.join(projectTools.config.outputDir, projectId);
    await fs.mkdir(outputDir, { recursive: true });

    for (const [filePath, content] of Object.entries(files)) {
        const fullPath = path.join(outputDir, filePath);
        const dir = path.dirname(fullPath);
        await fs.mkdir(dir, { recursive: true });
        await fs.writeFile(fullPath, content);
    }
    return { success: true, projectPath: outputDir };
}


// --- Exposed Tool Functions ---

async function createBasicWebsite({ title, description, sections, theme }) {
  try {
    // 1. Define the high-level requirements for the planner
    const requirements = {
      title: title || 'My Awesome Website',
      description: description || 'A website generated by Joe AI',
      sections: sections || ['home', 'about', 'contact'],
      theme: theme || 'modern'
    };

    // 2. Call the complex internal engine with the correct type and requirements
    const result = await projectTools.generateProject('website', requirements);

    if (!result.success) {
      throw new Error(result.error || 'Failed to generate project files.');
    }

    // 3. Save the generated files to the specified output directory
    await saveProjectToDisk(result.projectId, result.files);

    return { 
        success: true, 
        message: `Successfully created a new website named '${title}'.`,
        projectId: result.projectId,
        projectPath: path.join(projectTools.config.outputDir, result.projectId)
    };

  } catch (error) {
    return { success: false, error: `Failed to create website: ${error.message}` };
  }
}
createBasicWebsite.metadata = {
    name: "createBasicWebsite",
    description: "Creates a complete, production-ready static website with multiple sections and a customizable theme. This is the primary tool for building new websites from scratch.",
    parameters: {
        type: "object",
        properties: {
            title: { 
                type: "string", 
                description: "The main title of the website (e.g., 'My Personal Portfolio')." 
            },
            description: { 
                type: "string", 
                description: "A brief description of the website for SEO purposes."
            },
            sections: { 
                type: "array", 
                items: { type: "string" }, 
                description: "An array of page sections to include. Examples: ['home', 'about', 'services', 'contact']."
            },
            theme: { 
                type: "string", 
                description: "The visual theme for the website. Supported themes: 'professional', 'modern', 'minimal', 'creative', 'dark'.",
                enum: ['professional', 'modern', 'minimal', 'creative', 'dark']
            }
        },
        required: ["title", "description"]
    }
};

// FUTURE: Add more facade functions here for other project types
// async function createReactWebApp({ ... }) { ... }
// async function createExpressAPI({ ... }) { ... }

export default { createBasicWebsite };
